### ISSUE TITLE
[bug]: Cannot convert undefined value to object (AppKit)

### ISSUE THREAD

**Issue by lucaskraus** [reown-com/appkit-react-native#334]
### Description

Hey!

My project is a universal app with Next.js + Expo. The Reown SDK installed in Next app is working perfectly, but I just found out a bug when installing React Native SDK in the Expo project. 

After run all the steps in the Reown documentation, it's gives me an error. If I remove <AppKit /> from _layout.tsx, the app works normally.

Here's the error:

![Image](https://github.com/user-attachments/assets/1d3fa08f-f78b-4cc8-8b93-7fa590b0ff32)

` (NOBRIDGE) ERROR  Warning: TypeError: Cannot convert undefined value to object

This error is located at:
    in AppKit (created by RootLayoutNav)
    in QueryClientProvider (created by RootLayoutNav)
    in Hydrate (created by WagmiProvider)
    in WagmiProvider (created by RootLayoutNav)
    in ThemeProvider (created by RootLayoutNav)
    in ToastProvider (created by GluestackUIProvider)
    in PortalProvider (created by GluestackUIProvider)
    in RCTView (created by View)
    in View (created by CssInterop.View)
    in CssInterop.View (created by GluestackUIProvider)
    in GluestackUIProvider (created by RootLayoutNav)
    in RootLayoutNav (created by RootLayout)
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in AppContainer
    in main(RootComponent)`

 

### AppKit SDK version

@reown/appkit-wagmi-react-native: "1.2.3"

### Output of `npx react-native info`

System:
  OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Memory: 14.06 GB / 15.51 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 22.14.0
    path: ~/.nvm/versions/node/v22.14.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v22.14.0/bin/yarn
  npm:
    version: 11.2.0
    path: ~/.nvm/versions/node/v22.14.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: javac 22
    path: /home/lucas/.sdkman/candidates/java/current/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.79.0 is now available (your project is running on v0.76.9).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.79.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.9&to=0.79.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=linux".

### Expo Version (if applies)

Expo 52.0.44

### Steps to reproduce

- Run `yarn` in the root to install all dependencies
- Change Project ID in `const projectId = "SET_ID_HERE"` apps/expo-app/app/_layout.tsx
- Run `yarn run:expo` to initialize the Expo locally.
- Open Expo app in Android or iOS (I mainly using Android for testing purposes in my project)

### Snack, code example, screenshot, or link to a repository

https://github.com/lucaskraus/reown-reproducible-error

**Comment by ignaciosantise** [comment]
hey @lucaskraus 👋 sorry for the delay. The issue happens because there are two versions of valtio installed in your project. `1.13.x` for AppKit web and `1.11.2` for AppKit react-native, and apparently yarn is resolving to the incorrect version on native.

Adding `"valtio": "1.11.2"` in your expo app [package.json](https://github.com/lucaskraus/reown-reproducible-error/blob/c8ec95fba8091d3ee2f3738aec4fb1cbc6f313e6/apps/expo-app/package.json#L46) should fix the issue. Can you try that?

**Comment by ignaciosantise** [comment]
@dip-angelhack can you upload a video with the issue? what's the error?

**Comment by ignaciosantise** [comment]
@lucaskraus were you able to solve the issue?

**Comment by yucheng-Li** [comment]
> hey [@lucaskraus](https://github.com/lucaskraus) 👋 sorry for the delay. The issue happens because there are two versions of valtio installed in your project. `1.13.x` for AppKit web and `1.11.2` for AppKit react-native, and apparently yarn is resolving to the incorrect version on native.
> 
> Adding `"valtio": "1.11.2"` in your expo app [package.json](https://github.com/lucaskraus/reown-reproducible-error/blob/c8ec95fba8091d3ee2f3738aec4fb1cbc6f313e6/apps/expo-app/package.json#L46) should fix the issue. Can you try that?

It work for me, i meet the problem. 


 (NOBRIDGE) ERROR  Warning: TypeError: undefined is not an object (evaluating '_ref5[0]')

This error is located at:
    in AppKitButton (created by OtherOptions)
    in RCTSafeAreaView (created by OtherOptions)
    in OtherOptions (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)

**Comment by An0nym0usAng3l** [comment]
> "overrides": {
>     "valtio": "1.11.2"
>   },

This issue is still there and this resolution doesn't work for pnpm users. @ignaciosantise

**Comment by yucheng-Li** [comment]
已收到
