### ISSUE TITLE
[bug]: New version increased bundle size noticable

### ISSUE THREAD

**Issue by itsnyx** [reown-com/appkit-react-native#378]
### Description

Hello, I'm running on the latest version, and recent updates made my bundle size 30% bigger 
here is the screen shot of react native bundle visualizer 

 

<img width="1250" height="404" alt="Image" src="https://github.com/user-attachments/assets/29484e01-e754-425a-8b76-cfd8b76103fe" />

as you can see the @ wallet connect has 2 mb size which is alot !

also i get these error when i reload metro bundle 

```
WARN  Attempted to import the module "C:\myproject\node_modules\multiformats\cjs\src\basics.js" which is not listed in the "exports" of "C:\myproject\node_modules\multiformats" under the requested subpath "./cjs/src/basics.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\ethers\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\ethers\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\utils\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\utils\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\utils\node_modules\ox\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\utils\node_modules\ox\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\universal-provider\node_modules\@noble\curves\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\universal-provider\node_modules\@noble\curves\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\universal-provider\node_modules\viem\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\universal-provider\node_modules\viem\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\core\node_modules\@noble\curves\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\core\node_modules\@noble\curves\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "C:\myproject\node_modules\@walletconnect\core\node_modules\viem\node_modules\@noble\hashes\crypto.js" which is not listed in the "exports" of "C:\myproject\node_modules\@walletconnect\core\node_modules\viem\node_modules\@noble\hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
```

the versions : 
```
    "@reown/appkit-ethers-react-native": "^1.2.6",    
 "@walletconnect/react-native-compat": "^2.21.4", 
    "react": "19.0.0",
    "react-i18next": "^15.5.1",
    "react-native": "0.79.3",
```

### AppKit SDK version

    "@reown/appkit-ethers-react-native": "^1.2.6",    

### Output of `npx react-native info`

Running on windows

### Expo Version (if applies)

53

### Steps to reproduce

Simple project

### Snack, code example, screenshot, or link to a repository

Not provided

**Comment by itsnyx** [comment]
<img width="1914" height="863" alt="Image" src="https://github.com/user-attachments/assets/23362359-c9e7-417a-a435-d07f8c776e0b" />

this is full detail on this

**Comment by itsnyx** [comment]
<img width="1913" height="861" alt="Image" src="https://github.com/user-attachments/assets/576d38b1-69e5-4a2b-8048-f7e26fb05cca" />

this is what i had in previous versions ... trying to find what condition caused this 
also there was only 1 "@walletconnect/ethereum-provider" in yarn lock

**Comment by ignaciosantise** [comment]
@itsnyx can you add this to your package.json and run yarn install again? To solve the version issues

```
"resolutions": {
   "@walletconnect/universal-provider": "2.21.1"
}
```

**Comment by itsnyx** [comment]
after 100 times of running bundle visualiser i found out that 
upgrading from     "@reown/appkit-ethers-react-native": "^1.2.4", to latest version by doing yarn add @reown/appkit-ethers-react-native ethers will increase the bundle file size and you can't reverse this unless you have old yarn.lock file and changing back the version works... 

maybe it's my package manager (yarn) problem 
but yeah that's it ! 
hope i helped so you can reproduce 


this is after i fixed it 


<img width="1292" height="624" alt="Image" src="https://github.com/user-attachments/assets/fa07b89c-b6fa-4553-8a9b-ab762e4b77c4" />

**Comment by ignaciosantise** [comment]
@itsnyx im not sure i followed your solution, are you using an old yarn.lock? if so, you are probably still using the old version of appkit

**Comment by itsnyx** [comment]
@ignaciosantise  yes im on old arch

I will give the steps again so you can understand better

1- install app kit 1.2.4 

2- copy yarn.lock ( this will be referenced as old yarn.lock)

3-Update appkit library to latest version with 
`yarn add @reown/appkit-ethers-react-native ethers `


4- run npx bundle-visualiser and check the bundle size (it should be around 2MB)

5 - for getting rid of this I changed the version of app kit to 1.2.4 in package.json and did yarn install but this didn't reduce the bund;e size 
for actually getting this fixed after this update i replaced the new yarn.lock with old yarn.lock from step 2 then i did yarn install and it fixed

**Comment by ignaciosantise** [comment]
@itsnyx i think that's a very temporal solution until you install other dependency.

Adding this and running `yarn install` again will probably improve the bundle size. You'll still have an increased bundle but not that much. If you are also using viem, consider adding it also to resolutions.

```
"resolutions": {
   "@walletconnect/universal-provider": "2.21.1",
   "@walletconnect/ethereum-provider": "2.21.1",
   "@walletconnect/utils": "2.21.1"
}
```

Anyways, im speaking with the team to solve the issue but it might take a while.

**Comment by itsnyx** [comment]
hey @ignaciosantise 
Thanks i will check that 

this is reproduce repo 

https://github.com/itsnyx/appkit-reproduce-repo


---

the increase in bundle size only occurs in versions greater than1.2.4 !

the version 1.2.4 is ok

**Comment by ignaciosantise** [comment]
Im closing this as it's not directly related to the SDK, but to wagmi connectors that install a lot of unused stuff. 

I updated some internal deps to solve part of the issue on other libs, but doesn't completely solve it.

In the new [docs](https://docs.reown.com/appkit/react-native/core/installation#wagmi), i added a note to add resolutions to solve the version conflicts, and it should also decrease the bundle size.

<img width="692" height="606" alt="Image" src="https://github.com/user-attachments/assets/e8d4670a-18e3-449d-83f0-a6b06ec5e758" />

**Comment by itsnyx** [comment]
Hello @ignaciosantise  thanks for your attention

Just a reminder Im using ethers => @reown/appkit-ethers-react-native not wagmi and still get increased bundlesize

**Comment by ignaciosantise** [comment]
Ah you're right! Updating to v2 will probably solve your issue 🎉  the new ethers package doesn't use the problematic package anymore

**Comment by itsnyx** [comment]
@ignaciosantise  yes I just updated to v2 and everything works correctly 

Thanks for you awesome work keep it up 🔥
